### ISSUE TITLE
Site update

### ISSUE THREAD

**Issue by woutervddn** [0x20/hackerspaces.be#16]
Hi All

So one of our Brixel Members (Kefcom) editted the address a couple of months ago. 7 days ago this request was merged but the website still isn't updated. When will it see the latest changes?

**Comment by HansF** [comment]
I've sent a mail to the guy that does the hosting, sorry for late reply.

**Comment by woutervddn** [comment]
Cool, thx... Hopefully that speeds it up a little...

**Comment by warddr** [comment]
updated, need to check my crons, sorry it took so long.

No idea where the () behind the adres comes from

**Comment by HansF** [comment]
maybe add some contact info regarding the site if there are future issues?

2015-06-09 2:07 GMT+02:00 Ward De Ridder <notifications@github.com>:
