### ISSUE TITLE
Website was not deployed in over a year.

### ISSUE THREAD

**Issue by hellekin** [0x20/hackerspaces.be#37]
Although #36 was merged just one year and one day ago, the result does not appear on https://hackerspaces.be/

![_sudo make me a sandwich_](https://imgs.xkcd.com/comics/sandwich.png)

**Comment by HansF** [comment]
It's has seemed to be moved to [here](https://gitlab.com/hackerspacesbe/website/).
Someone is updating that site with the content from this one, and then we'll put a better readme.md here directing people to the right place.
